version: '3.4'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    volumes:
      - ./db:/db

